<?php
// $Id: simple_spam_filter.module,v0.1  2010/12/23

/**
 * Implementation of hook_menu().
 */
function simple_spam_filter_menu() {
  $menu = array();
  $menu['admin/settings/simple_spam_filter'] = array(
    'title' => t('Simple Spam Filter Settings'),
    'description' => t('Configure Simple Spam Filter'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simple_spam_filter_settings_form'),
    'access arguments' => array('config simple spam filter settings'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $menu;
}

/**
 * Implementation of hook_perm()
 */
function simple_spam_filter_perm() {
  return array(
    'config simple spam filter settings',
  );
}

/**
 * Implementation of hook_form_alter().
 * Add a textfield which is invisible for end-user (by using css hack)
 * And a validate hook to check the field value
 *
 */
function simple_spam_filter_form_alter(&$form, &$form_state, $form_id) {
  $spam_validate_enabled = false;
  $form_list = variable_get('simple_spam_filter_form_list', array());
  $ip_blacklist = variable_get('simple_spam_filter_ip_blacklist', array());

  if (!empty($ip_blacklist) && in_array($_SERVER['REMOTE_ADDR'], $ip_blacklist)) {
    $spam_validate_enabled = true;
    $form['simple_s_filter_identified'] = array(
      '#type' => 'hidden',
      '#value' => true,
    );
  }
  else if (!empty($form_list) && in_array($form_id, $form_list)) {
    $spam_validate_enabled = true;
    drupal_add_css(drupal_get_path('module', 'simple_spam_filter') .'/simple_spam_filter.css');
    $form['simple_s_filter_field'] = array(
      '#type' => 'textfield',
      '#title' => 'Simple Filter',
      '#prefix' => '<div id="simple_s_filter_div">',
      '#suffix' => '</div>',
      '#description' => t('This field is for computer-generated email only and should not be visible. If you can see it, please ignore it.'),
    );
  }

  if ($spam_validate_enabled) {
    array_unshift($form['#validate'], simple_spam_filter_form_validate);
  }
}

/**
 * Spam field Validate Hook
 */
function simple_spam_filter_form_validate($form, &$form_state) {
  if (
    $form['simple_s_filter_identified'] ||
    !empty($form_state['values']['simple_s_filter_field'])
  ) {
    $error_message = variable_get('simple_spam_filter_error_message', 'Sorry you failed security check, pat down time!');
    form_set_error('simple_s_filter_fields', $error_message);
  }
}

/**
 * Simple spam filter settings form with config of 
 * 1. form name list
 * 2. error message
 */

function simple_spam_filter_settings_form() {

  $form['simple_spam_filter_form_list'] = array(
    '#type' => 'textarea',
    '#title' => t('Enable Simple Spam Filter For following Forms'),
    '#description' => t('Please provide new line separated form names'),
    '#default_value' => implode("\n", variable_get('simple_spam_filter_form_list',array())),
  );
  $form['simple_spam_filter_ip_blacklist'] = array(
    '#type' => 'textarea',
    '#title' => t('Block following IPs for form submission'),
    '#description' => t('Please provide Line separated IPs'),
    '#default_value' => variable_get('simple_spam_filter_ip_blacklist', NULL),
    '#default_value' => implode("\n", variable_get('simple_spam_filter_ip_blacklist',array())),
  );
  $form['simple_spam_filter_error_message'] = array(
    '#type' => 'textfield',
    '#title' => t('Error Message when spam is detected'),
    '#description' => t('Please provide Line separated form names'),
    '#default_value' => variable_get('simple_spam_filter_error_message', NULL),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}

/**
 * helper function to convert line separated string to array
 * 
 * @param string $setting 
 * @return array
 */
function simple_spam_filter_explode_setting($setting=NULL) {
  $ret = array();
  if (!empty($setting)) {
    $setting = explode("\n",$setting);
    foreach($setting as $s) {
      if (trim($s)) $ret[] = trim($s);
    }
  }
  return $ret;
}

/**
 * Simple spam filter settings form submit 
 */
function simple_spam_filter_settings_form_submit($form, $form_state) {
  variable_set('simple_spam_filter_form_list', simple_spam_filter_explode_setting($form_state['values']['simple_spam_filter_form_list']));
  variable_set('simple_spam_filter_ip_blacklist', simple_spam_filter_explode_setting($form_state['values']['simple_spam_filter_ip_blacklist']));
  variable_set('simple_spam_filter_error_message', $form_state['values']['simple_spam_filter_error_message']);
  drupal_set_message('Simple Spam Filter settings updated.');
}
